### PR TITLE
class 01 exercise 04

### PR DESCRIPTION
**Pull request by CarineOliveira**
# Description

Exercise C01-E04

Student Name: Carine Oliveira

## Type of change

- [ x ] Exercise Submission (one exercise per PR)
- [ x ] This PR is just for **one** exercise of a class
- [  ] PR name follows the pattern `<github-username>/<exercise-number>`
- [ x ] Added exercise files inside folder `/classes/<class- number>/exercises/<exercise-number>/<github-username>/`
- [ ] Review [exercise submission steps](./README.md#Exercises)
- [ ] Class content (instructors/admins)
- [ ] Documentation update
- [ ] Repo management

### CODE REVIEW

**Comment by CarineOliveira** [comment]
You're right, the access is public. How should I proceed to access the S3 when not public?

**Comment by kikobr82** [comment]
when the S3 access is not public, you won;t be able to access it through http/https request.

You'll need to use the aws cli tool to be able to interact with s3.
If you attached an instance role with proper permissions to S3 to the EC2 instance, you should be able to get the file through the command:
`aws s3 cp s3://academy-bucket/logo.png . ` 
Try to execute this command and if that works update your file with this command and its output, so we can approve and merge this PR.

If it doesn't work, we can try to troubleshoot what is wrong..

ps: just make sure that the path that I wrote in the command provided is the right one for your file.

**Comment by CarineOliveira** [comment]
S3 is not public anymore.

I've previously tried this command "aws s3 cp s3://academy-bucket/logo.png ." when the S3 bucket wasn't public but didn't work at the time, but now I see I was missing the full stop at the end.

**Comment by denstorti** [comment]
> S3 is not public anymore.
> 
> I've previously tried this command "aws s3 cp s3://academy-bucket/logo.png ." when the S3 bucket wasn't public but didn't work at the time, but now I see I was missing the full stop at the end.

The `.` in the end of the `s3 cp` command means the destination folder. Good work.

When trying a command that should work and it is not working, check the docs for the AWS CLI. You can do it by typing the command with `help` in the end. 
In this case, `aws s3 cp help`

**Pull request merged**
