### PR TITLE
cyberjames/c04-iac03

### PR DESCRIPTION
**Pull request by cyberjames**
# Description

Exercise (e.g. C01-E01): c04-iac03

Student Name: James Corteciano

> A brief explanation of what has been done.
> Copied the same Terraform files in [previous exercise](https://github.com/devopsacademyau/academy/blob/master/classes/04class/exercises/c04-iac02) for the [Changing Values (c04-iac03)](https://github.com/devopsacademyau/academy/blob/master/classes/04class/exercises/c04-iac03/README.md) exercise including my answer for the [question(s)](https://github.com/devopsacademyau/academy/blob/master/classes/04class/exercises/c04-iac03/ANSWER.md).

## Type of change

- [x] Exercise Submission (one exercise per PR)
  - [x] This PR is just for **one** exercise of a class
  - [x] PR name follows the pattern `<github-username>/<exercise-number>`
  - [x] Added exercise files inside folder `/classes/<class- number>/exercises/<exercise-number>/<github-username>/`
	- [ ] Review [exercise submission steps](./README.md#Exercises)
- [ ] Class content (instructors/admins)
- [ ] Documentation update
- [ ] Repo management

### CODE REVIEW

**Review by crofty-contino — APPROVED** [review]
LGTM

**Comment by crofty-contino** [comment]
@cyberjames can you please check if you can resolve this conflict on the readme? Let me know if you need a hand

**Comment by cyberjames** [comment]
Hi @crofty-contino , probably I need your help with this. Just let me know when you are free. Thanks

**Comment by cyberjames** [comment]
I have deleted the wrong README.md due to the wrong branch being used. @crofty-contino

**Pull request merged**
