### PR TITLE
cyberjames/c01-git01

### PR DESCRIPTION
**Pull request by cyberjames**
# Description

Exercise (e.g. C01-E01): c01-git01

Student Name: James Corteciano

> A brief explanation of what has been done.
> For git merging exercise, I switched to the bugFix branch, did a commit, same thing to main branch, and did the `git merge bugFix`. For rebasing exercise, the same steps previously but I used `git rebase main` command. Lastly, to solve revert and reset exercise by using `git reset HEAD~1`.

## Type of change

- [x] Exercise Submission (one exercise per PR)
  - [x] This PR is just for **one** exercise of a class
  - [x] PR name follows the pattern `<github-username>/<exercise-number>`
  - [x] Added exercise files inside folder `/classes/<class- number>/exercises/<exercise-number>/<github-username>/`
	- [ ] Review [exercise submission steps](./README.md#Exercises)
- [ ] Class content (instructors/admins)
- [ ] Documentation update
- [ ] Repo management

### CODE REVIEW

**Review by crofty-contino — CHANGES_REQUESTED** [review]
`classes/01class/exercises/c01-git01/README.md` looks to be the readme for the class excercises.

Can you please create a subfolder cyberjames in this location and then move the readme to  `classes/01class/exercises/c01-git01/cyberjames/README.md`

**Comment by cyberjames** [comment]
oh right, didn't realised I missed my subfolder 😂. Thanks mate 👍

**Review by cyberjames — COMMENTED** [review]
Moved my answer to the correct directory.
- Created subdirectory classes/01class/exercises/c01-git01/cyberjames
- Moved classes/01class/exercises/c01-git01/README.md onto classes/01class/exercises/c01-git01/cyberjames

**Review by crofty-contino — APPROVED** [review]
LGTM

**Pull request merged**
