### PR TITLE
starkmatt/c04 iam01

### PR DESCRIPTION
**Pull request by starkmatt**
# Description

Exercise c04-iam

Student Name: Matt G
> A brief explanation of what has been done.

## Type of change

- [x] Exercise Submission (one exercise per PR)
  - [x] This PR is just for **one** exercise of a class
  - [ ] PR name follows the pattern `<github-username>/<exercise-number>`
  - [ ] Added exercise files inside folder `/classes/<class- number>/exercises/<exercise-number>/<github-username>/`
	- [ ] Review [exercise submission steps](./README.md#Exercises)
- [ ] Class content (instructors/admins)
- [ ] Documentation update
- [ ] Repo management

### CODE REVIEW

**Comment by denstorti** [comment]
The solution looks good, Matt. Can you merge or rebase on master again? The labeler is failing.

I am curious why you merged master 9 times in a row too 😀

**Comment by denstorti** [comment]
I just saw that you are using a forked repo.

Please refer to my comment in Christina's PR, she has the same issue as yours.

https://github.com/devopsacademyau/academy/pull/490#issuecomment-612701327

**Comment by starkmatt** [comment]
> The solution looks good, Matt. Can you merge or rebase on master again? The labeler is failing.
> 
> I am curious why you merged master 9 times in a row too 😀

All done :D!
Thanks for guiding me through to that!
Seeing the red cross on my PR was annoying :P

**Comment by denstorti** [comment]
It seems the labeler job is still failing :( 

@kikobr82 , is it related to the token not being fetched for forked repos?

**Comment by caiocezart** [comment]
I will get this merged as it's not Matt's fault

**Pull request merged**
