### PR TITLE
Add files README.md and cli_commands.txt for exercise c04-iam01

### PR DESCRIPTION
**Pull request by carloshz4**
# Description

Exercise (e.g. C01-E01): c04-iam01

Student Name: Carlos Zambrano

> Added files README.md and cli_commands.txt inside folder /classes/02class/exercises/c04-iam01/carloshz4/

## Type of change

- [ ] Exercise Submission (one exercise per PR)
  - [ ] This PR is just for **one** exercise of a class
  - [ ] PR name follows the pattern `<github-username>/<exercise-number>`
  - [ ] Added exercise files inside folder `/classes/<class- number>/exercises/<exercise-number>/<github-username>/`
	- [ ] Review [exercise submission steps](./README.md#Exercises)
- [ ] Class content (instructors/admins)
- [ ] Documentation update
- [ ] Repo management

### CODE REVIEW

**Comment by carloshz4** [comment]
Thanks @alanlima. I forgot those, will add them and re-submit.  Cheers

**Comment by carloshz4** [comment]
Hi @alanlima, just added the missing commands.  Just curious, do you (as a reviewer) get notified when a new commit (with the corrections) is added to the PR?

**Comment by alanlima** [comment]
> Hi @alanlima, just added the missing commands. Just curious, do you (as a reviewer) get notified when a new commit (with the corrections) is added to the PR?

Hey @carloshz4 
Yep, I just received an e-mail with your commit 😅
btw, since I started the review, I will receive all changes in this PR. But it is possible to turn it off.

How are you going with the exercises? any question?

**Comment by carloshz4** [comment]
> > Hi @alanlima, just added the missing commands. Just curious, do you (as a reviewer) get notified when a new commit (with the corrections) is added to the PR?
> 
> Hey @carloshz4
> Yep, I just received an e-mail with your commit 😅
> btw, since I started the review, I will receive all changes in this PR. But it is possible to turn it off.
> 
> How are you going with the exercises? any question?

Thanks @alanlima for explaining this to me.     At the moment I am good, if I get stuck with something I'll let you know :)

**Pull request merged**
