### PR TITLE
Commit by mail2kvanitha

### PR DESCRIPTION
**Pull request by mail2kvanitha**
# Description

Exercise (e.g. C01-E01): Class/exercise/mail2kvanitha/c01-e01

Student Name:mail2kvanitha

> A brief explanation of what has been done.
Created Repo with my name/class-exercise name. Created folder with my name and created file. Pushed the changes to Origin.

## Type of change

- [x] Exercise Submission (one exercise per PR)
  - [x] This PR is just for **one** exercise of a class
  - [x] PR name follows the pattern `<github-username>/<exercise-number>`
  - [ ] Added exercise files inside folder `/classes/<class- number>/exercises/<exercise-number>/<github-username>/`
	- [ ] Review [exercise submission steps](./README.md#Exercises)
- [ ] Class content (instructors/admins)
- [ ] Documentation update
- [ ] Repo management

### CODE REVIEW

**Comment by mail2kvanitha** [comment]
Updated c01-git01, c01-git02, c01-git03, c01-git04 Answer files. Please review and advise. Thanks. This is awesome good course, and I learnt a lot. Thanks for your wonderful support.

**Comment by caiocezart** [comment]
the file `classes/01class/exercises/c01-e01/mail2kvanitha/c01-e01-git01.txt` is not part of any exercise. Can you delete please?

**Comment by denstorti** [comment]
Hello Vanitha.

PRs should have content of just a single exercise. So you will need 1 branch for each of the exercises, and there will be 1 PR per exercise.

The answer files for this exercise should be called `README.md` and not `c01-git01.txt` for example.

Please check the instructions here https://github.com/devopsacademyau/academy#exercises
and let us know if you get stuck fixing it

**Comment by mail2kvanitha** [comment]
Hi Denis, Kiko, Caio,
Hope you are doing good. I finished all the git and aws exercises and pushed to master. Could you please advise if anything else is pending? 

Thanks and Have a great weekend.

Thanks and Regards,
Vanitha
+61 424358917

**Comment by kikobr82** [comment]
Hi Vanitha.
We haven't received any exercise from you. There is probably something that you're not doing right. In order to submit an exercise, you must consider the following.
- You need to create one branch per exercise and submit a PR from each of this branch to this Repository
- Each branch you create for a particular exercise must be created from an updated master branch( git checkout master; git pull; git checkout -b "yourname/exercise")

The information provided [here](https://github.com/devopsacademyau/academy#exercises) should help you in this process. If still not sure, get into the slack channel and send us a message so we can help you out.

Thanks.

**Comment by mail2kvanitha** [comment]
Hi Kiko,
I could see my work in GitHub master. Please see below screenshot for the
same. I followed the same steps in the information page shared. Not sure
what i am missing.

[image: image.png]


*Thanks and Regards,*
*Vanitha*
*+61 424358917*

**Comment by mail2kvanitha** [comment]
Please see attached snapshot from my local git repository.  PLease let me
know what's your mobile number and time to call you. Thanks.

[image: image.png]

[image: image.png]

**Comment by mail2kvanitha** [comment]
some more snapshots from the local GIT repository.

[image: image.png]

**Comment by kikobr82** [comment]
Hi Vanitha.
I was able to find your code in branches. You need to create a pull request now so we can evaluate your answers and merge the code to the master branch.
Can you, please, create a Pull Request for each exercise from the branch you have to the mater branch?

Let me know if you need any help found that.

**Pull request closed without merging**
